### ISSUE TITLE
Two UnificationRules.SubstRights in callAbductionRules.

### ISSUE THREAD

**Issue by yutakang** [TyGuS/suslik#30]
`UnificationRules.SubstRight` appears twice within [`callAbductionRules`](https://github.com/TyGuS/suslik/blob/5b1491927502b2bee1443890761dc5b077949307/src/main/scala/org/tygus/suslik/synthesis/tactics/PhasedSynthesis.scala#L98): in [Line 100](https://github.com/TyGuS/suslik/blob/5b1491927502b2bee1443890761dc5b077949307/src/main/scala/org/tygus/suslik/synthesis/tactics/PhasedSynthesis.scala#L100)  and [Line 117](https://github.com/TyGuS/suslik/blob/5b1491927502b2bee1443890761dc5b077949307/src/main/scala/org/tygus/suslik/synthesis/tactics/PhasedSynthesis.scala#L117).

Is this intentional?

**Comment by ilyasergey** [comment]
I don’t think so — probably an artifact of some experiments.

Ilya

From: Yutaka Ng ***@***.***>
Reply to: TyGuS/suslik ***@***.***>
Date: Wednesday, 14 July 2021 at 19:23
To: TyGuS/suslik ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TyGuS/suslik] Two UnificationRules.SubstRights in callAbductionRules. (#30)


UnificationRules.SubstRight appears twice within callAbductionRules<https://github.com/TyGuS/suslik/blob/5b1491927502b2bee1443890761dc5b077949307/src/main/scala/org/tygus/suslik/synthesis/tactics/PhasedSynthesis.scala#L98>: in Line 100<https://github.com/TyGuS/suslik/blob/5b1491927502b2bee1443890761dc5b077949307/src/main/scala/org/tygus/suslik/synthesis/tactics/PhasedSynthesis.scala#L100> and Line 117<https://github.com/TyGuS/suslik/blob/5b1491927502b2bee1443890761dc5b077949307/src/main/scala/org/tygus/suslik/synthesis/tactics/PhasedSynthesis.scala#L117>.

Is this intentional?

**Comment by yutakang** [comment]
I see. I will remove the duplication at least from the `evolutionary` branch.
